let anitomyscript = require("../build/build.js");
let instance = new anitomyscript.Anitomy();
console.log(instance.options());
console.log(instance.parse("Detective Conan - 316-317 [DCTP][2411959B].mkv"));
console.log(instance.elements().empty_capacity());
console.log(instance.elements().empty_lookup(anitomyscript.ElementCategory.kElementAnimeTitle));
console.log(instance.elements().size());
console.log(instance.elements().get(anitomyscript.ElementCategory.kElementAnimeTitle));
console.log(instance.elements().get_all(anitomyscript.ElementCategory.kElementEpisodeNumber).get(1));
console.log(instance.elements().count(anitomyscript.ElementCategory.kElementEpisodeNumber));